# Generated by Django 6.0.5 on 2026-05-07 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_role_profile_roles"),
        ("diyprojects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
            ),
        ),
    ]
