# Generated by Django 6.0.5 on 2026-05-07 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diyprojects", "0002_alter_projectreview_reviewer"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectreview",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
